### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by RChadwick7** [ripxorip/pico_guitar_to_midi#1]
Does this need any software on the PC side? Does the USB emulate a MIDI?

**Comment by ripxorip** [comment]
Hi, sorry for the late reply. No software needed on the PC side. USB emulate a MIDI port. However it relies on libMiGiC which has not yet been officially released for ARM. BR, Philip

**Comment by spamogh** [comment]
Hey, 
I wanted to do this as my final year project for DSP and stumbled upon your YouTube video 
I am a beginner at this so could you explain to me about the libmiggic thing I didn’t understand a word of that

**Comment by craigy90** [comment]
Hi,

Guitar to midi was someone else's project that I was following a few years
ago I think. I never tried it.

I did use pi pico as a usb midi device, pico is good for that.

Cheers,
Craig
